### PR TITLE
Update to Java 8 compatible extractor v0.22.7 and fix API changes

### PR DESCRIPTION
**Pull request by Jtfk**
#### What is it?
- [x] Bug fix (user facing)
- [ ] Feature (user facing)
- [ ] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
Upstream extractor requires Java 11 to build since v0.22.5.

This updates to a modified version of the extractor (https://github.com/Jtfk/NewPipeExtractor-j8), which is based on v0.22.7 upstream with backports to support Java 8

#### Known Issue
Some YouTube comments will have HTML tags shown unless `https://github.com/TeamNewPipe/NewPipe/pull/9631` is introduced (might be out of scope for this repo).

#### Testing apk

[update-extractor-v0.22.7.zip](https://github.com/XiangRongLin/NewPipe-preuinified/files/12346741/update-extractor-v0.22.7.zip)
(this is a debug build and shall use for testing only)

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by XiangRongLin** [comment]
Sorry, but im not changing the extractor to one thats not from `com.github.TeamNewPipe`. I can't and will not verify whats done in a fork of the extractor.

As written in the repo short description and in the pinned issue: feel free to take over the project. I can leave a note to tell people to go to your fork.

**Comment by Jtfk** [comment]
Thanks, I understood it. I will try use the official version for it but it requires AGP update which may change the build script and compatibility. Would you mind if I create another PR for that?

My opinion is that if another fork is created, reinstallation is needed since the signature is different. ~~The setting need to be migrated manually since the build in "export database" does not cover it~~(apparently it does).

**Comment by XiangRongLin** [comment]
> My opinion is that if another fork is created, reinstallation is needed since the signature is different

There wont be a way around this in the long term. At some point someone will have to take over or the fork dies as it currently is.

**Comment by MapleWheels** [comment]
Thanks for this update @Jtfk , hopefully this one lasts for a while. 

I wish I was a Java stack dev (am CSharp) or I'd take over.

@XiangRongLin  If you're willing continue maintaining ONLY in so far as to testing/approving PRs, I'd be willing to (and I think others) toss a few bucks your way.

Right now, NewPipe is undergoing a rewrite with no news/roadmap and all work outside of critical bugfixing is halted. My hopes is this lives long enough until they update NewPipe frontend.

**Pull request closed without merging**
